### Site Settings ###
title               : Dmitry Ursa
description         : >-
                      "Hi, i do web stuff! Love flexbox, WordPress and clean js"
baseurl             : "/"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : dmitryursa.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/blog.html
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Dmitry Ursa
  image             : https://avatars2.githubusercontent.com/u/43716464?s=460&v=4
  telegram           : DmitryUrsa
#  behance           : your_username
# dribbble          : your_username
#  email             : username@domain.com
#  facebook          : your_username
#  github            : your_username
# gitlab            : your_username
# instagram         : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
